//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminProductChanx
    {
        public int userID { get; set; }
        public int productID { get; set; }
        public string productName { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
    
        public virtual AdminLoginDetail AdminLoginDetail { get; set; }
    }
}
